# Configuration for synthetic error insertion
# Adjust these rates based on desired error frequency

error_rates:
  punctuation:
    quote_spaces: 0.05          # Add spaces inside quotes: "hello" -> " hello "
    missing_quotes: 0.03        # Remove quotes (first, last, or both)
    punctuation_outside_quotes: 0.04  # Move punctuation outside quotes
  
  typography:
    dropped_letters: 0.08       # Remove random letters from words
    swapped_letters: 0.06       # Swap adjacent letters
    dropped_words: 0.02         # Remove entire words (not first/last)
    swapped_words: 0.01         # Swap adjacent words
  
  spacing:
    spaces_around_punctuation: 0.06  # Add spaces before punctuation
    missing_spaces: 0.04        # Remove spaces between words
  
  homophones:
    substitution_rate: 0.10     # Replace with common homophones
  
  contractions:
    dropped_nt: 0.03           # Remove "n't" from contractions
  
  keyboard_neighbors:
    substitution_rate: 0.07    # Replace with adjacent keyboard keys

# General settings
preserve_ratio: 0.3            # Fraction of examples to keep unchanged
max_errors_per_chunk: 3        # Maximum errors per text chunk
min_chunk_length: 50           # Minimum text length to apply errors