model:
  # model_name: "unsloth/gemma-3-4b-pt-unsloth-bnb-4bit"
  model_name: "./gemma-3-4b-pt-gec"
  max_seq_length: 2048
  load_in_4bit: true
  load_in_8bit: false
  full_finetuning: false

peft:
  r: 32
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  lora_alpha: 64
  lora_dropout: 0
  bias: "none"
  use_gradient_checkpointing: "unsloth"
  random_state: 3407
  use_rslora: true
  loftq_config: null

training:
  dataset_text_field: "text"
  max_length: 768
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 4
  warmup_steps: 200
  max_steps: -1
  num_train_epochs: 2
  eval_strategy: "steps"
  eval_steps: 100
  n_eval_samples: 500
  learning_rate: 2e-5
  logging_steps: 1
  optim: "adamw_8bit"
  weight_decay: 0.1
  lr_scheduler_type: "linear"
  seed: 3407
  output_dir: "outputs"
  save_steps: 100
  save_total_limit: 3
  report_to: "mlflow"
  resume_from_checkpoint: null  # Set to checkpoint path or "auto" to auto-detect
  early_stopping_patience: 3
  # logging_dir: "outputs/runs/Sep14_16-39-27_yellowstone-ubuntu"

data:
  dataset_path: "data/gec-dataset"
  system_prompt_path: "config/prompt.txt"
  chat_template: "gemma3"

inference:
  temperature: 1.0
  top_p: 0.95
  top_k: 64
  max_new_tokens: 125
  cache_implementation: "dynamic"

masking:
  instruction_part: "<start_of_turn>user\n"
  response_part: "<start_of_turn>model\n"
